### ISSUE TITLE
Supported archive types

### ISSUE THREAD

**Issue by Shea690901** [shoriminimoe/fish-extract#4]
If you support zip files you shouldn't have any problems with at least jar and xpi files. Both formats are just zip files themselves....
Just beware: neither of them uses a 'root directory' 😉

**Comment by shoriminimoe** [comment]
Good to know. Thanks for the tip!

**Comment by APT37** [comment]
These formats could easily be supported too:

- `.apk` files are also ZIP files: [apk (file format)](https://en.wikipedia.org/wiki/Apk_(file_format)?useskin=vector#Package_contents)
- `.rar` files are supported by p/7zip, though one would have to use the non-free package version (iirc).
